MES/MES/Models/MetaData/route.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MES.Models
{
    [MetadataType(typeof(routeMetaData))]
    public partial class route
    {
        private class routeMetaData
        {
            [Key]
            public int rowid { get; set; }

            [Display(Name = "流程編號")]
            [Required(ErrorMessage = "編號不可空白!")]
            public string r_no { get; set; }

            [Display(Name = "流程名稱")]
            [Required(ErrorMessage = "名稱不可空白!")]
            public string r_name { get; set; }

            [Display(Name = "備註")]
            public string remark { get; set; }

        }
    }
}

MES/MES/Models/ViewModel/RouteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;

namespace MES.Models
{
    public class RouteViewModel
    {
        public IPagedList<route> routesList { get; set; }

        public IPagedList<route_detail> route_detailsList { get; set; }
    }
}

MES/MES/Models/route.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class route
    {
        public int rowid { get; set; }
        public string r_no { get; set; }
        public string r_name { get; set; }
        public string remark { get; set; }
    }
}

MES/MES/Controllers/RouteController.cs
using MES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;


namespace MES.Controllers
{
    public class RouteController : Controller
    {
        MESEntities db = new MESEntities();

        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult List( int page=0)
        {
            if (page > 0) AppSession.MasterPage = page;
            AppSession.MasterPageSize = 1;
            AppSession.DetailPageSize =5;
            RouteViewModel model = new RouteViewModel();
            model.routesList = db.route.OrderBy(m => m.r_no)
                .ToPagedList(AppSession.MasterPage, AppSession.MasterPageSize);

            //保存目前表頭的主鍵值
            AppSession.MasterKeyValue = model.routesList.FirstOrDefault().r_no;

            model.route_detailsList = db.route_detail
                .Where(m => m.r_no == AppSession.MasterKeyValue)
                .OrderBy(m => m.sort_no)
                .ToPagedList(AppSession.DetailPage, AppSession.DetailPageSize);

            foreach (var item in model.route_detailsList)
            {
                item.proc_name = GetProcessName(item.proc_no);
            }

            return View(model);
        }


        public ActionResult MasterPage(int page = 1)
        {
            AppSession.MasterPage = page;
            AppSession.DetailPage = 1;
            return RedirectToAction("List");
        }

        public ActionResult DetailPage(int page = 1)
        {
            AppSession.DetailPage = page;
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster()
        {
            var data=db.route.OrderByDescending(m => m.r_no)
                .FirstOrDefault();

            string str_route_no = "001";
            if (data != null)
            {
                if (string.IsNullOrEmpty(data.r_no)) str_route_no = "001";
                str_route_no = (int.Parse(data.r_no) + 1).ToString().PadLeft(3, '0');
            }

            route model = new route()
            {
                r_no = str_route_no,
                r_name = ""
            };
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster(route model)
        {
            if (!ModelState.IsValid) return View(model);

            bool bln_error = false;
            var check1 = db.route.Where(m => m.r_no == model.r_no).FirstOrDefault();
            if (check1 != null) { ModelState.AddModelError("r_no", "編號重複"); bln_error = true; }
            var check2 = db.route.Where(m => m.r_name == model.r_name).FirstOrDefault();
            if (check2 != null) { ModelState.AddModelError("r_name", "名稱重複!"); bln_error = true; }
            if (bln_error) return View(model);

            db.route.Add(model);
            db.SaveChanges();

            //新增完計算新資料所在頁數
            AppSession.MasterPage = db.route.OrderBy(m => m.r_no)
                .ToList().FindIndex(m => m.r_no == model.r_no);
            AppSession.MasterPage++;
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail()
        {
            var data = db.route_detail
                .Where(m => m.r_no == AppSession.MasterKeyValue)
                .OrderByDescending(m => m.sort_no)
                .FirstOrDefault();
            string str_sort_no = "01";
            if (data != null)
            {
                if (string.IsNullOrEmpty(data.sort_no)) str_sort_no = "00";
                str_sort_no = (int.Parse(data.sort_no) + 1).ToString().PadLeft(2, '0');
            }

            route_detail model = new route_detail()
            {
                r_no = AppSession.MasterKeyValue,
                sort_no = str_sort_no,
                proc_no = "",
                max_value = 0,
                min_value = 0,
                remark = ""
            };
            ViewBag.ProcessList = GetProcessList("");
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail(route_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.route_detail
                    .Where(m => m.r_no == model.r_no)
                    .Where(m => m.proc_no == model.proc_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("proc_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList("");
                return View(model);
            }

            route_detail data = new route_detail()
            {
                r_no = AppSession.MasterKeyValue,
                sort_no = model.sort_no,
                proc_no = model.proc_no,
                max_value = model.max_value,
                min_value = model.min_value,
                remark = model.remark
            };

            db.route_detail.Add(data);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(int id)
        {
            var model = db.route.Where(m => m.rowid == id).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(route model)
        {
            if (!ModelState.IsValid) return View(model);

            bool bln_error = false;
            var check1 = db.route.Where(m => m.r_no == model.r_no && m.rowid != model.rowid).FirstOrDefault();
            if (check1 != null) { ModelState.AddModelError("r_no", "編號重複"); bln_error = true; }
            var check2 = db.route.Where(m => m.r_name == model.r_name && m.rowid != model.rowid).FirstOrDefault();
            if (check2 != null) { ModelState.AddModelError("r_name", "名稱重複!"); bln_error = true; }
            if (bln_error) return View(model);

            var data = db.route.Where(m => m.rowid == model.rowid).FirstOrDefault();
            data.r_no = model.r_no;
            data.r_name = model.r_name;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(int id)
        {
            var model = db.route_detail.Where(m => m.rowid == id).FirstOrDefault();
            ViewBag.ProcessList = GetProcessList(model.proc_no);
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(route_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.route_detail
                    .Where(m => m.rowid != model.rowid)
                    .Where(m => m.r_no == model.r_no)
                     .Where(m => m.proc_no == model.proc_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("proc_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList(model.proc_no);
                return View(model);
            }

            var data = db.route_detail.Where(m => m.rowid == model.rowid).FirstOrDefault();
            data.sort_no = model.sort_no;
            data.proc_no = model.proc_no;
            data.min_value = model.min_value;
            data.max_value = model.max_value;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult DeleteMaster(int id)
        {
            var model1 = db.route.Where(m => m.rowid == id).FirstOrDefault();

            //先刪除明細
            var model2 = db.route_detail
                .Where(m => m.r_no == model1.r_no).ToList();
            foreach (var item in model2)
            {
                db.route_detail.Remove(item);
            }
            db.SaveChanges();

            //再刪除表頭
            db.route.Remove(model1);
            db.SaveChanges();

            //表頭刪除後,表頭頁數 -1 , 明細從第 1 頁開始
            if (AppSession.MasterPage > 1) AppSession.MasterPage--;
            AppSession.DetailPage = 1;
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult DeleteDetail(int id)
        {
            var model = db.route_detail.Where(m => m.rowid == id).FirstOrDefault();
            if (model != null)
            {
                db.route_detail.Remove(model);
                db.SaveChanges();
            }

            //明細刪除後,頁數 -1
            if (AppSession.DetailPage > 1) AppSession.DetailPage--;

            return RedirectToAction("List");
        }

        /// <summary>
        /// 取得製程名稱
        /// </summary>
        /// <param name="procNo">製程代號</param>
        /// <returns></returns>
        private string GetProcessName(string procNo)
        {
            var data = db.process.Where(m => m.proc_no == procNo).FirstOrDefault();
            return (data == null) ? "" : data.proc_name;
        }

        /// <summary>
        /// 取得製程下拉資料
        /// </summary>
        /// <param name="procNo">製程代號</param>
        /// <returns></returns>
        private List<SelectListItem> GetProcessList(string procNo)
        {
            bool bln_select = false;

MES/MES/Views/Route/CreateDetail.cshtml
@model MES.Models.route_detail

@{
    ViewBag.Title = "流程明細新增";
}

@section styles {
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>流程明細新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(m => m.rowid)
                            @Html.HiddenFor(m => m.r_no)

                            <div class="row row-group">
                                @Html.LabelFor(model => model.sort_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.sort_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.sort_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.proc_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.proc_no, new SelectList(ViewBag.ProcessList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.proc_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.min_value, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.min_value, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.min_value, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.max_value, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.max_value, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.max_value, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Route", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/Route/CreateMaster.cshtml
@model MES.Models.route

@{
    ViewBag.Title = "流程主檔新增";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>流程主檔新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row row-group">
                                @Html.LabelFor(model => model.r_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.r_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.r_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.r_name, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.r_name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.r_name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Route", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/Route/EditDetail.cshtml
@model MES.Models.route_detail

@{
    ViewBag.Title = "EditDetail";
}

@section styles {
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal mt-2">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-5 col-md-6 col-sm-10 ">
                    <div class="panel panel-group border border-secondary">
                        <div class="panel panel-primary">
                            <div class="panel panel-heading  bg-info">
                                <h4>流程明細修改</h4>
                            </div>
                            <div class="panel panel-body mt-2 mb-2">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.rowid)
                                @Html.HiddenFor(model => model.r_no)

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.sort_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.sort_no, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.sort_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.proc_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.proc_no, new SelectList(ViewBag.ProcessList, "Value", "Text" ), new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.proc_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.min_value, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.min_value, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.min_value, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.max_value, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.max_value, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.max_value, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    <div class="col-md-12">
                                        <input type="submit" value="儲存" class="btn btn-primary" />
                                        @Html.ActionLink("返回列表", "List", "Route", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/Route/EditMaster.cshtml
@model MES.Models.route

@{
    ViewBag.Title = "流程主檔修改";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-4 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>流程主檔修改</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.rowid)

                            <div class="row row-group">
                                @Html.LabelFor(model => model.r_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.r_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.r_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.r_name, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.r_name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.r_name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="儲存" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Route", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}