MES/MES/Models/MetaData/workorder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MES.Models
{
    [MetadataType(typeof(workorderMetaData))]
    public partial class workorder
    {
        private class workorderMetaData
        {
            [Key]
            public int rowid { get; set; }

            [Display(Name = "製令編號")]
            [Required(ErrorMessage = "編號不可空白!")]
            public string workorder_no { get; set; }

            [Display(Name = "製令日期")]
            [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
            [Required(ErrorMessage = "日期不可空白!")]
            public Nullable<System.DateTime> workorder_date { get; set; }

            //[Display(Name = "訂單編號")]
            //[Required(ErrorMessage = "編號不可空白!")]
            //public string order_no { get; set; }

            [Display(Name = "產品編號")]
            [Required(ErrorMessage = "編號不可空白!")]
            public string product_no { get; set; }

            [Display(Name = "流程編號")]
            [Required(ErrorMessage = "編號不可空白!")]
            public string route_no { get; set; }

            [Display(Name = "數量")]
            [Required(ErrorMessage = "數量不可空白!")]
            public Nullable<int> qty { get; set; }

            [Display(Name = "備註")]
            public string remark { get; set; }

        }
    }
}

MES/MES/Models/ViewModel/WorkOrderViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MES.Models
{
    public class WorkOrderViewModel
    {

        public IPagedList<order_detail> order_detailsList { get; set; }
        public IPagedList<workorder> workordersList { get; set; }
        public IPagedList<workorder_detail> workorder_detailsList { get; set; }


        //[Display(Name="製令編號")]
        //public string workorder_no { get; set; }

        //[Display(Name = "製令日期")]
        //public DateTime workorder_date { get; set; }

        //[Display(Name = "訂單編號")]
        //public string order_no { get; set; }

        //[Display(Name = "產品編號")]
        //public string product_no { get; set; }

        //[Display(Name = "流程編號")]
        //public string route_no { get; set; }

        //[Display(Name = "數量")]
        //public int qty { get; set; }

        //[Display(Name = "製程順序")]
        //public string sort_no { get; set; }

        //[Display(Name = "製程編號")]
        //public string process_no { get; set; }

        //[Display(Name = "機台編號")]
        //public string machine_no { get; set; }

        //[Display(Name = "輸入數量")]
        //public int in_qty { get; set; }

        //[Display(Name = "損壞數量")]
        //public int bad_qty { get; set; }

        //[Display(Name = "需調整數量")]
        //public int adj_qty { get; set; }

        //[Display(Name = "輸出數量")]
        //public int out_qty { get; set; }
    }
}

MES/MES/Models/workorder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workorder
    {
        public int rowid { get; set; }
        public string workorder_no { get; set; }
        public Nullable<System.DateTime> workorder_date { get; set; }
        public string oder_no { get; set; }
        public string product_no { get; set; }
        public string route_no { get; set; }
        public Nullable<int> qty { get; set; }
        public string remark { get; set; }
    }
}

MES/MES/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MES.Models;
using PagedList;

namespace MES.Controllers
{
    public class WorkOrderController : Controller
    {
        MESEntities db = new MESEntities();

        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult List(int page = 0)
        {
            if (page > 0) AppSession.MasterPage = page;
            AppSession.MasterPageSize = 1;
            AppSession.DetailPageSize = 5;
            WorkOrderViewModel model = new WorkOrderViewModel();

            model.workordersList = db.workorder
                .OrderBy(m => m.workorder_no)
                .ToPagedList(AppSession.MasterPage, AppSession.MasterPageSize);

            AppSession.MasterKeyValue = model.workordersList.FirstOrDefault().workorder_no;

            model.workorder_detailsList = db.workorder_detail
                .Where(m => m.workorder_no == AppSession.MasterKeyValue)
               .OrderBy(m => m.sort_no)
               .ToPagedList(AppSession.DetailPage, AppSession.DetailPageSize);
            return View(model);
        }

        public ActionResult MasterPage(int page = 1)
        {
            AppSession.MasterPage = page;
            AppSession.DetailPageSize = 1;
            return RedirectToAction("List");
        }

        public ActionResult DetailPage(int page = 1)
        {
            AppSession.DetailPage = page;
            return RedirectToAction("List");
        }





        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster()
        {

            int int_seq = 0;
            string str_today = DateTime.Now.ToString("yyyyMMdd");
            var data = db.workorder
                .Where(m => m.workorder_no.Contains(str_today))
                .OrderByDescending(m => m.workorder_no)
                .FirstOrDefault();
            if (data != null)
            {
                if (data.workorder_no.Length == 11)
                    int_seq = int.Parse(data.workorder_no.Substring(8, 3));
            }
            int_seq++;
            string str_workorder_no = str_today + int_seq.ToString().PadLeft(3, '0');

            workorder model = new workorder()
            {
                workorder_no = str_workorder_no,
                workorder_date = DateTime.Now,
                product_no = "",
                route_no = "",
                qty = 0
            };
            ViewBag.ProductList = GetProductList("");
            ViewBag.RouteList = GetRouteList("");
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster(workorder model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.workorder
                    .Where(m => m.workorder_no == model.workorder_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("workorder_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {
                ViewBag.ProductList = GetProductList("");
                ViewBag.RouteList = GetRouteList("");
                return View(model);
            }

            workorder data = new workorder()
            {
                workorder_no = AppSession.MasterKeyValue,
                workorder_date = model.workorder_date,
                product_no = model.product_no,
                route_no = model.route_no,
                qty = model.qty
            };

            db.workorder.Add(model);
            db.SaveChanges();

            //新增完計算新資料所在頁數
            AppSession.MasterPage = db.workorder.OrderBy(m => m.workorder_no)
                .ToList().FindIndex(m => m.workorder_no == model.workorder_no);
            AppSession.MasterPage++;
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail()
        {
            var data = db.workorder_detail
                .Where(m => m.workorder_no == AppSession.MasterKeyValue)
                .OrderByDescending(m => m.sort_no)
                .FirstOrDefault();
            string str_sort_no = "01";
            if (data != null)
            {
                if (string.IsNullOrEmpty(data.sort_no)) str_sort_no = "00";
                str_sort_no = (int.Parse(data.sort_no) + 1).ToString().PadLeft(2, '0');
            }

            workorder_detail model = new workorder_detail()
            {
                workorder_no = AppSession.MasterKeyValue,
                sort_no = str_sort_no,
                process_no = "",
                machine_no = "",
                in_qty = 0,
                bad_qty = 0,
                adj_qty = 0,
                out_qty = 0,
                remark = ""
            };
            var in_start = db.workorder.Where(m => m.workorder_no == AppSession.MasterKeyValue).FirstOrDefault();
            if (model.sort_no == "01")
            {
                model.in_qty = (int)in_start.qty;
            }
            ViewBag.ProcessList = GetProcessList("");
            ViewBag.MAchineList = GetMachineList("");
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail(workorder_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.workorder_detail
                    .Where(m => m.workorder_no == model.workorder_no)
                    .Where(m => m.sort_no == model.sort_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("sort_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList("");
                ViewBag.MAchineList = GetMachineList("");
                return View(model);
            }

            workorder_detail data = new workorder_detail()
            {
                workorder_no = AppSession.MasterKeyValue,
                sort_no = model.sort_no,
                process_no = model.process_no,
                machine_no = model.machine_no,
                in_qty = model.in_qty,
                bad_qty = model.bad_qty,
                adj_qty = model.adj_qty,
                out_qty = Count(model.in_qty, model.bad_qty, model.adj_qty)
            };

            var pre_out_qty = db.workorder_detail.Where(m => m.workorder_no == AppSession.MasterKeyValue).OrderByDescending(m => m.sort_no).FirstOrDefault();

            if (pre_out_qty != null)
            {
                if (data.in_qty != pre_out_qty.out_qty)
                {
                    data.remark = "數量錯誤";
                }
                else
                {
                    data.remark = "";
                }
            }

            db.workorder_detail.Add(data);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public int Count(int in_qty, int bad_qty, int adj_qty)
        {
            int out_qty = in_qty - adj_qty - bad_qty;
            return out_qty;
        }


        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(int id)
        {
            var model = db.workorder.Where(m => m.rowid == id).FirstOrDefault();
            ViewBag.RouteList = GetRouteList(model.route_no);
            ViewBag.ProductList = GetProductList(model.product_no);
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(workorder model)
        {

            bool bln_error = false;

            if (!ModelState.IsValid) bln_error = true;
            if (bln_error)
            {
                ViewBag.RouteList = GetRouteList(model.route_no);
                ViewBag.ProductList = GetProductList(model.product_no);
                return View(model);
            }

            var data = db.workorder.Where(m => m.rowid == model.rowid).FirstOrDefault();
            data.workorder_no = model.workorder_no;
            data.workorder_date = model.workorder_date;
            data.product_no = model.product_no;
            data.route_no = model.route_no;
            data.qty = model.qty;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(int id)
        {
            var model = db.workorder_detail.Where(m => m.rowid == id).FirstOrDefault();
            ViewBag.ProcessList = GetProcessList(model.process_no);
            ViewBag.MAchineList = GetMachineList(model.machine_no);
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(workorder_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.workorder_detail
                    .Where(m => m.rowid != model.rowid)
                    .Where(m => m.workorder_no == model.workorder_no)
                     .Where(m => m.sort_no == model.sort_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("sort_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList(model.process_no);
                ViewBag.MAchineList = GetMachineList(model.machine_no);
                return View(model);
            }

MES/MES/Views/WorkOrder/CreateDetail.cshtml
@model MES.Models.workorder_detail

@{
    ViewBag.Title = "製令明細新增";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>製令明細新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(m => m.rowid)
                            @Html.HiddenFor(m => m.workorder_no)

                            <div class="row row-group">
                                @Html.LabelFor(model => model.sort_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.sort_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.sort_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.process_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.process_no, new SelectList(ViewBag.ProcessList, "Value", "Text"), new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.process_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.machine_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.machine_no, new SelectList(ViewBag.MachineList, "Value", "Text"), new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.machine_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.in_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.in_qty, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.in_qty, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                @Html.LabelFor(model => model.bad_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.bad_qty, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.bad_qty, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                @Html.LabelFor(model => model.adj_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.adj_qty, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.adj_qty, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "WorkOrder", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/WorkOrder/CreateMaster.cshtml
@model MES.Models.workorder

@{
    ViewBag.Title = "製令主檔新增";
}

@section scripts{
    <script src="@Url.Content("~/Scripts/datepicker.js")"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>製令主檔新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row row-group">
                                @Html.LabelFor(model => model.workorder_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.workorder_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.workorder_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.workorder_date, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.workorder_date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.workorder_date, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.product_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.product_no, new SelectList(ViewBag.ProductList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.product_no, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                @Html.LabelFor(model => model.route_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.route_no, new SelectList(ViewBag.RouteList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.route_no, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "WorkOrder", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/WorkOrder/EditDetail.cshtml
@model MES.Models.workorder_detail

@{
    ViewBag.Title = "製令明細修改";
}

@section styles {
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal mt-2">
        <div class="container-fluid">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-5 col-md-6 col-sm-10 ">
                    <div class="panel panel-group border border-secondary">
                        <div class="panel panel-primary">
                            <div class="panel panel-heading  bg-info">
                                <h4>製令明細修改</h4>
                            </div>
                            <div class="panel panel-body mt-2 mb-2">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.rowid)
                                @Html.HiddenFor(model => model.workorder_no)

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.sort_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.sort_no, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.sort_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.process_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.process_no, new SelectList(ViewBag.ProcessList, "Value", "Text"), new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.process_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.machine_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.machine_no, new SelectList(ViewBag.MachineList, "Value", "Text"), new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.machine_no, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    @Html.LabelFor(model => model.in_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.in_qty, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.in_qty, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row row-group">
                                    @Html.LabelFor(model => model.bad_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.bad_qty, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.bad_qty, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row row-group">
                                    @Html.LabelFor(model => model.adj_qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.adj_qty, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.adj_qty, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="row row-group">
                                    <div class="col-md-12">
                                        <input type="submit" value="儲存" class="btn btn-primary" />
                                        @Html.ActionLink("返回列表", "List", "WorkOrder", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}