MES/MES/Models/MetaData/re_complete.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MES.Models
{
    [MetadataType(typeof(re_completeMetaData))]
    public partial class re_complete
    {
        private class re_completeMetaData
        {
            [Key]
            public int rowid { get; set; }

            [Display(Name = "訂單編號")]
            [Required(ErrorMessage = "編號不可空白!")]
            public string order_no { get; set; }

            [Display(Name = "回報單編號")]
            [Required(ErrorMessage = "名稱不可空白!")]
            public string re_complete_no { get; set; }

            [Display(Name = "回報單日期")]
            [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
            public DateTime re_complete_date { get; set; }

        }
    }
}

MES/MES/Models/ViewModel/re_completeViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MES.Models
{
    public class re_completeViewModel
    {

        public IPagedList<order> ordersList { get; set; }
        public IPagedList<re_complete> re_completesList { get; set; }
        public IPagedList<re_complete_detail> re_complete_detailsList { get; set; }
        
    }
}

MES/MES/Models/re_complete.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_complete
    {
        public int rowid { get; set; }
        public string order_no { get; set; }
        public string re_complete_no { get; set; }
        public Nullable<System.DateTime> re_complete_date { get; set; }
        public string remark { get; set; }
    }
}

MES/MES/Controllers/Re_CompleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MES.Models;
using MES.Models.ViewModel;
using PagedList;

namespace MES.Controllers
{
    public class Re_CompleteController : Controller
    {
        MESEntities db = new MESEntities();

        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult List(int page=0)
        {
            if (page > 0) AppSession.MasterPage = page;
            AppSession.MasterPageSize = 1;
            AppSession.DetailPageSize = 5;
            re_completeViewModel model = new re_completeViewModel();
            model.re_completesList = db.re_complete.OrderBy(m => m.re_complete_no)
                .ToPagedList(AppSession.MasterPage, AppSession.MasterPageSize);

            //保存目前表頭的主鍵值
            AppSession.MasterKeyValue = model.re_completesList.FirstOrDefault().re_complete_no;

            model.re_complete_detailsList = db.re_complete_detail
                .Where(m => m.re_complete_no == AppSession.MasterKeyValue)
                .OrderBy(m => m.re_complete_no)
                .ToPagedList(AppSession.DetailPage, AppSession.DetailPageSize);

            return View(model);
        }

        public ActionResult MasterPage(int page = 1)
        {
            AppSession.MasterPage = page;
            AppSession.DetailPageSize = 1;
            return RedirectToAction("List");
        }

        public ActionResult DetailPage(int page = 1)
        {
            AppSession.DetailPage = page;
            return RedirectToAction("List");
        }


        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster()
        {
            int int_seq = 0;
            string str_today = DateTime.Now.ToString("yyyyMMdd");
            var data = db.re_complete
                .Where(m => m.re_complete_no.Contains(str_today))
                .OrderByDescending(m => m.re_complete_no)
                .FirstOrDefault();
            if (data != null)
            {
                if (data.re_complete_no.Length == 11)
                    int_seq = int.Parse(data.re_complete_no.Substring(8, 3));
            }
            int_seq++;
            string str_re_complete_no = str_today + int_seq.ToString().PadLeft(3, '0');

            re_complete model = new re_complete()
            {
                re_complete_no = str_re_complete_no,
                order_no="",
                re_complete_date = DateTime.Now
            };
            ViewBag.OrderList = GetOrderList("");
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateMaster(re_complete model)
        {
            bool bln_error = false;

            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.re_complete
                    .Where(m => m.re_complete_no == model.re_complete_no)
                    .FirstOrDefault();
                if (check1 != null) { ModelState.AddModelError("re_complete_no", "編號重複"); bln_error = true; }
            }
            if (bln_error)
            {

                ViewBag.OrderList = GetOrderList("");
                return View(model);
            }

            re_complete data = new re_complete()
            {
                re_complete_no = AppSession.MasterKeyValue,
                order_no=model.order_no,
                re_complete_date = model.re_complete_date
            };

            db.re_complete.Add(model);
            db.SaveChanges();

            //新增完計算新資料所在頁數
            AppSession.MasterPage = db.re_complete.OrderBy(m => m.re_complete_no)
                .ToList().FindIndex(m => m.re_complete_no == model.re_complete_no);
            AppSession.MasterPage++;
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail()
        {
            var data = db.re_complete_detail
                .Where(m => m.re_complete_no == AppSession.MasterKeyValue)
                .OrderByDescending(m => m.proc_no)
                .FirstOrDefault();


            re_complete_detail model = new re_complete_detail()
            {
                re_complete_no = AppSession.MasterKeyValue,
                proc_no = "",
                mach_no = "",
                value1 = 0,
                value2 = 0,
                value3 = 0,
                user_no = "",
                start_time = DateTime.Now,
                end_time = DateTime.Now,
                qty = 0,
                remark = ""
            };
            ViewBag.ProcessList = GetProcessList("");
            ViewBag.MachineList = GetMachineList("");
            ViewBag.UserList = GetUserList("");
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult CreateDetail(re_complete_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.re_complete_detail
                    .Where(m => m.re_complete_no == model.re_complete_no)
                    .FirstOrDefault();
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList("");
                ViewBag.MachineList = GetMachineList("");
                ViewBag.UserList = GetUserList("");
                return View(model);
            }

            re_complete_detail data = new re_complete_detail()
            {

                re_complete_no = AppSession.MasterKeyValue,
                proc_no = model.proc_no,
                mach_no = model.mach_no,
                value1 = model.value1,
                value2 = model.value2,
                value3 = model.value3,
                user_no = model.user_no,
                start_time = model.start_time,
                end_time = model.end_time,
                qty = model.qty,
                remark = model.remark
            };

            db.re_complete_detail.Add(data);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(int id)
        {
            var model = db.re_complete.Where(m => m.rowid == id).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditMaster(re_complete model)
        {
            if (!ModelState.IsValid) return View(model);

            bool bln_error = false;
            var check1 = db.re_complete.Where(m => m.re_complete_no == model.re_complete_no && m.rowid != model.rowid).FirstOrDefault();
            if (check1 != null) { ModelState.AddModelError("re_complete_no", "編號重複"); bln_error = true; }
            if (bln_error) return View(model);

            var data = db.re_complete.Where(m => m.rowid == model.rowid).FirstOrDefault();
            data.re_complete_no = model.re_complete_no;
            data.re_complete_date = model.re_complete_date;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(int id)
        {
            var model = db.re_complete_detail.Where(m => m.rowid == id).FirstOrDefault();
            ViewBag.ProcessList = GetProcessList(model.proc_no);
            ViewBag.MachineList = GetMachineList(model.mach_no);
            ViewBag.UserList = GetUserList(model.user_no);
            return View(model);
        }

        [HttpPost]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult EditDetail(re_complete_detail model)
        {
            bool bln_error = false;
            if (!ModelState.IsValid) bln_error = true;
            if (!bln_error)
            {
                var check1 = db.re_complete_detail
                    .Where(m => m.rowid != model.rowid)
                    .Where(m => m.re_complete_no == model.re_complete_no)
                    .FirstOrDefault();
            }
            if (bln_error)
            {
                ViewBag.ProcessList = GetProcessList(model.proc_no);
                ViewBag.MachineList = GetMachineList(model.mach_no);
                ViewBag.UserList = GetUserList(model.user_no);
                return View(model);
            }

            var data = db.re_complete_detail.Where(m => m.rowid == model.rowid).FirstOrDefault();
            data.proc_no = model.proc_no;
            data.mach_no = model.mach_no;
            data.value1 = model.value1;
            data.value2 = model.value2;
            data.value3 = model.value3;
            data.user_no = model.user_no;
            data.start_time = model.start_time;
            data.end_time = model.end_time;
            data.qty = model.qty;
            data.remark = model.remark;
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        [LoginAuthorize(RoleList = "User,Admin")]
        public ActionResult DeleteMaster(int id)
        {
            var model1 = db.re_complete.Where(m => m.rowid == id).FirstOrDefault();

            //先刪除明細
            var model2 = db.re_complete_detail
                .Where(m => m.re_complete_no == model1.re_complete_no).ToList();
            foreach (var item in model2)
            {
                db.re_complete_detail.Remove(item);
            }
            db.SaveChanges();

            //再刪除表頭
            db.re_complete.Remove(model1);
            db.SaveChanges();

            //表頭刪除後,表頭頁數 -1 , 明細從第 1 頁開始
            if (AppSession.MasterPage > 1) AppSession.MasterPage--;
            AppSession.DetailPage = 1;

MES/MES/Views/Re_Complete/CreateDetail.cshtml
@model MES.Models.re_complete_detail

@{
    ViewBag.Title = "回報單明細新增";
}
@section scripts{
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datetimepicker.zh-TW.js")"></script>
}
<link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-datetimepicker.min.css")">


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>回報單明細新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(m => m.rowid)
                            @Html.HiddenFor(m => m.re_complete_no)

                            <div class="row row-group">
                                @Html.LabelFor(model => model.proc_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.proc_no, new SelectList(ViewBag.ProcessList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.proc_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.mach_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.mach_no, new SelectList(ViewBag.MachineList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.mach_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.value1, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.value1, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.value1, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.value2, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.value2, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.value2, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.value3, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.value3, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.value3, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.user_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.user_no, new SelectList(ViewBag.UserList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.user_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    <div class="input-group date start_datetime">
                                        @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    <div class="input-group date end_datetime">
                                        @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                                    </div>
                                    @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Re_Complete", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $('.start_datetime').datetimepicker({
        language: 'zh-TW',
        locale: {
            format: "yyyy/MM/dd HH:mm:ss"
        },
        startDate: new Date,
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1,

    });

    $('.end_datetime').datetimepicker({
        language: 'zh-TW',
        locale: {
            format: "yyyy/MM/dd HH:mm:ss"
        },
        startDate: new Date,
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        forceParse: 0,
        showMeridian: 1,
    });
</script>

MES/MES/Views/Re_Complete/CreateMaster.cshtml
@model MES.Models.re_complete

@{
    ViewBag.Title = "回報單主檔新增";
}

@section scripts{
    <script src="@Url.Content("~/Scripts/datepicker.js")"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>回報單主檔新增</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row row-group">
                                @Html.LabelFor(model => model.order_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.order_no, new SelectList(ViewBag.OrderList, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.order_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.re_complete_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.re_complete_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.re_complete_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.re_complete_date, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.re_complete_date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.re_complete_date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="新增" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Re_Complete", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

MES/MES/Views/Re_Complete/EditMaster.cshtml
@model MES.Models.re_complete

@{
    ViewBag.Title = "回報單主檔修改";
}

@section scripts{
    <script src="@Url.Content("~/Scripts/datepicker.js")"></script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-2">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 col-md-6 col-sm-10 ">
                <div class="panel panel-group border border-secondary">
                    <div class="panel panel-primary">
                        <div class="panel panel-heading  bg-info">
                            <h4>回報單主檔修改</h4>
                        </div>
                        <div class="panel panel-body mt-2 mb-2">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.rowid)

                            <div class="row row-group">
                                @Html.LabelFor(model => model.re_complete_no, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.re_complete_no, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.re_complete_no, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row row-group">
                                @Html.LabelFor(model => model.re_complete_date, htmlAttributes: new { @class = "control-label col-md-3 ColumnHeader" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.re_complete_date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.re_complete_date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row row-group">
                                <div class="col-md-12">
                                    <input type="submit" value="儲存" class="btn btn-primary" />
                                    @Html.ActionLink("返回列表", "List", "Re_Complete", new { page = AppSession.MasterPage }, new { @class = "btn btn-success" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}